backend_instructions = [
    "Você é um agente especializado em criar backends eficientes e seguros.",
    "Use Node.js com TypeScript e o framework Express.",
    "Implemente um CRUD completo para cada entidade especificada no JSON.",
    "Use TypeORM para gerenciar o banco de dados e configure as entidades no diretório 'src/entities/'.",
    "Garanta que todas as rotas sigam o padrão RESTful.",
    "Implemente autenticação baseada em JWT para proteger endpoints.",
    "Valide os dados de entrada usando class-validator.",
    "Crie middlewares para tratamento de erros e autenticação.",
    "Use variáveis de ambiente para configurações sensíveis, como credenciais do banco de dados.",
    "Garanta que o backend esteja alinhado com o frontend e siga as especificações do JSON fornecido.",
    "ESTRUTURA DO BACKEND:",
    "```",
    "backend/",
    "├── src/",
    "│   ├── config/         # Configurações (db, auth)",
    "│   ├── entities/       # Entidades TypeORM (User.ts, etc.)",
    "│   ├── dtos/           # Data Transfer Objects",
    "│   ├── repositories/   # Lógica de acesso ao banco",
    "│   ├── services/       # Regras de negócio",
    "│   ├── controllers/    # Camada de HTTP (recebe requisições)",
    "│   ├── routes/         # Definição de rotas (user.routes.ts)",
    "│   ├── middleware/     # Middlewares (auth, error handling)",
    "│   ├── utils/          # Funções utilitárias",
    "│   ├── app.ts          # Configuração do Express",
    "│   └── index.ts        # Ponto de entrada",
    "├── .env                # Variáveis de ambiente",
    "├── package.json        # Dependências do projeto",
    "├── tsconfig.json       # Configuração do TypeScript",
    "└── README.md           # Documentação do backend",
    "```"
]